INSERT INTO product (name, description, price, stock, image)
VALUES ('Lindby Eldarion Hängeleuchte mit Holzbalken, 4-fl.',
        'Mit der Hängeleuchte Eldarion etabliert sich ein Stück Natur im Alltag. Denn die Leuchte besteht aus einem echten Holzast. Dank der naturbelassen Optik scheint jeder Ast einzigartig. Die kleinen Einkerbungen und Verfärbungen, die individuell sind, da es sich um ein Naturprodukt handelt, machen die Leuchte erst besonders.',
        '139.90', 4,
        'https://lw-cdn.com/images/C7CCA93B2891/k_3045c86aec266d1eb9ffaf6547e7423e;w_1600;h_1600;q_70/lindby-eldarion-haengeleuchte-mit-holzbalken-4-fl.webp'),
       ('Lucande Hayley LED-Hängelampe, 9-flammig, gold',
        'Ein gehobenes Design und moderne LED-Technik zeichnen die besondere LED-Hängeleuchte Hayley aus. Sowohl der runde Baldachin als auch die filigranen Metallelemente, die die Unterseite der Glaskugelschirme einfassen, wurden mit einem goldenem Finish versehen.',
        '419.90', 7,
        'https://lw-cdn.com/images/1A8079DB5163/k_7745d8a08f0ad1b32fbdc18e24733b97;w_1600;h_1600;q_70/lucande-hayley-led-haengelampe-9-flammig-gold.webp'),
       ('Lindby Evengeline LED-Deckenleuchte',
        'Die LED-Deckenlampe Evengeline überzeugt mit ihrem frischen und abwechslungsreichen Aussehen. Ihr Leuchtenkörper ist aus Aluminium gefertigt und in Schwarz lackiert. An ihrer Deckenhalterung sind vier Lichtkreise horizontal versetzt angebracht, sodass eine interessante Form entsteht. Im Inneren der Kreise sind festverbaute LEDs angebracht und erzeugen durch die runde Form ein interessantes Licht, welches kreisförmige Muster an die Decke reflektiert.',
        '139.90', 7,
        'https://lw-cdn.com/images/EDDBE74B704A/k_7673f900df6e017fe6362d0e1adbfc4e;w_1600;h_1600;q_70/lindby-evengeline-led-deckenleuchte.webp'),
       ('Stoff-Deckenlampe Vasilia in Schwarz-Gold, 3-fl.',
        'Mit den drei individuell verstellbaren Leuchten der formschön gestalteten Deckenlampe Vasilia können auch größere Räume stimmungsvoll erhellt werden.',
        '64.90', 1,
        'https://lw-cdn.com/images/627EFBB63923/k_ea3f45ff4f2e2993aa1ed99a732f771c;w_1600;h_1600;q_70/stoff-deckenlampe-vasilia-in-schwarz-gold-3-fl.webp'),
       ('Geschwungene Kristalldeckenleuchte Shine',
        'Kristalle sind seit jeher vor allem wegen ihrer lichtreflektierenden Eigenschaften beliebt. Für diese besondere Wirkung ist diese Deckenleuchte mit ihren zahlreichen hängenden Ketten geradezu ein Paradebeispiel. Das von den insgesamt 5 Leuchtmitteln abgegebene Licht wird in vielfacher Weise von den Kristallen aufgefangen und mit einem glamourös und erhaben wirkenden Funkeln an den Raum zurückgegeben.',
        '7549.90', 1,
        'https://lw-cdn.com/images/F06C630ADA2C/k_70b7143a40c627748e00b782b712db26;w_1600;h_1600;q_70/geschwungene-kristalldeckenleuchte-shine.webp'),
       ('Lindby Lengla LED-Stehleuchte in Schwarz',
        'Die stilvolle LED-Stehleuchte Lengla präsentiert sich in einem markanten Look ganz in Schwarz. Diese besondere Lichtquelle hat ein modernes Design in Form eines in die Länge gezogenen Zylinders und passt deshalb wunderbar in zeitgenössisches Interieur.',
        '179.90', 3,
        'https://lw-cdn.com/images/6726B9A97CCB/k_3d7f251fd82589eda8f02b1319c475cb;w_1600;h_1600;q_70/lindby-lengla-led-stehleuchte-in-schwarz.webp'),
       ('GRUPA Arigato Stehleuchte, zweiflammig, schwarz',
        'Mit vielen Einrichtungskonzepten kombinierbar und flexibel in der Lichtabgabe, ist die Stehleuchte Arigato des kroatischen Herstellers GRUPA ein äußerst vielseitiger Lichtspender.',
        '829.90', 0,
        'https://lw-cdn.com/images/D82D3C16A522/k_a547742910a72192bed496022dc7f0e2;w_1600;h_1600;q_70/grupa-arigato-stehleuchte-zweiflammig-schwarz.webp'),
       ('Lindby Florentino Tischleuchte, Stoff und Keramik',
        'Diese Tischleuchte ist ein schöner Allrounder, vor allem für klassische Umgebungen. Der Lampenschirm verjüngt sich nach oben hin etwas, ist von oben betrachtet oval und er besteht aus weißem Stoff, der eine sehr weiche, gemütliche Lichtabstrahlung erlaubt.',
        '79.90', 6,
        'https://lw-cdn.com/images/F6CE5BAD8CB5/k_62be3e1ffa0dc4859908f8b875f6b820;w_1600;h_1600;q_70/lindby-florentino-tischleuchte-stoff-und-keramik.webp'),
       ('Lindby Linor LED-Weinflaschenlampe dunkelgrün Akku',
        'Garantiert wird diese Tischlampe Sie überzeugen, denn sie kann unkompliziert in einer Weinflasche positioniert werden. Die Tischleuchte ist mit einer Möglichkeit zum Dimmen, die für eine angenehme Wohlfühlatmosphäre sorgt, ausgestattet.',
        '37.90', 2,
        'https://lw-cdn.com/images/A717008BD7CA/k_5cd8fd06bae024650d1d3816fb0f41ff;w_1600;h_1600;q_70/lindby-linor-led-weinflaschenlampe-dunkelgruen-akku.webp'),
       ('Echte Bankerlampe TULSI',
        'Die Banker-Leuchte TULSI vereint auf klassische Weise Tradition und wertige Handarbeit. Sie punktet im Wohnzimmer ebenso wie im Büro, und kann auch Hotelzimmern den letzten Schliff geben.',
        '363.90', 1,
        'https://lw-cdn.com/images/6347AC0C04C8/k_cff7e891832950907f2265a224a7ea96;w_1600;h_1600;q_70/echte-bankerlampe-tulsi.webp')
;

INSERT INTO specification (name, value, product_fk)
VALUES ('Fassung', 'E27', 1),
       ('Dimmbar', 'Ja', 1),
       ('Material', 'Eisen, Holz', 1),
       ('Länge (in cm)', '116', 1),
       ('Breite (in cm)', '17.5', 1),
       ('Leuchtmittel inklusive', 'Ja', 2),
       ('Abhängung in cm', '150', 2),
       ('Farbe', 'klar, gold', 2),
       ('Lichtfarbe', 'warmweiss (3.000 K)', 2),
       ('Lichtfarbe', 'warmweiss (3.000 K)', 3),
       ('Material', 'Aluminium, Metall, Silikon', 3),
       ('Material', 'Stoff, Metall', 4),
       ('Leuchtmittel', '4 x 10 W', 4),
       ('Farbe', 'schwarz, gold', 4),
       ('Dimmbar', 'Ja', 4),
       ('Dimmer', 'Nicht enthalten', 4),
       ('Fassung', 'G9', 5),
       ('Länge (in cm)', '100', 5),
       ('Breite (in cm)', '12', 5),
       ('Leichtmittel inklusive', 'Nein', 5),
       ('Material', 'Kristall, Metall', 5),
       ('Höhe (in cm)', '103.5', 6),
       ('Sonstige Masse', 'Länge Kabel 180 cm', 6),
       ('Leuchtmittel', '2 x 70 W', 7),
       ('Fassung', 'E27', 7),
       ('Höhe (in cm)', '170', 7),
       ('Höhenverstellbar', 'Ja', 7),
       ('Material', 'Stoff, Keramik', 8),
       ('Breite (in cm)', '35.5', 8),
       ('Höhe (in cm)', '47', 8),
       ('Fassung', 'E27', 8),
       ('Dimmer', 'mit Touchdimmer', 9),
       ('Farbe', 'dunkelgrün', 9),
       ('Leuchtmittel inklusive', 'Ja', 9),
       ('Fassung', 'E27', 10),
       ('Leuchtmittel', '1 x 60 W', 10),
       ('Höhe (in cm)', '50', 10)
;


